s= set()
n=input("Enter number1: ")
s.add(n)
n=input("Enter number2: ")
s.add(n)                    
n=input("Enter number3: ")
s.add(n)
n=input("Enter number4: ")
s.add(n)
n=input("Enter number5: ")
s.add(n)
n=input("Enter number6: ")
s.add(n)
n=input("Enter number7: ")
s.add(n)
n=input("Enter number8: ")
s.add(n)

print("Unique numbers are: ", s)