import pyautogui
import time
import random

# Delay so you have time to click inside VS Code
print("You have 5 seconds to click in your VS Code editor...")
time.sleep(5)

# Some random Python code snippets to "type"
snippets = [
    "'Hello, World!'",
]

for _ in range(800):
    line = random.choice(snippets)
    pyautogui.write(line, interval=0.39)  # interval = typing speed
    pyautogui.press("enter")
    time.sleep(0.9)  # pause between lines
'''
def greet(name) return f'Hello {name}'
print('Hello, World!')
if True
    print('Condition met')
    print('Hello, World!')
    def greet(name) return f'Hello {name}'
    for i in range(5) print(i)
    class Bot
        def run(self)
                print('Running...')
                for i in range(5) print(i)
                for i in range(5) print(i)
                for i in range(5) print(i)
                for i in range(5) print(i)
                if True
                    print('Condition met')
                    if True
                        print('Condition met')
                        if True
                            print('Condition met')
                            for i in range(5) print(i)
                            for i in range(5) print(i)
                            class Bot
                                def run(self)
                                        print('Running...')
                                        print('Hello, World!')
                                        for i in range(5) print(i)
                                        for i in range(5) print(i)
                                        class Bot
                                            def run(self)
                                                    print('Running...')
                                                    print('Hello, World!')
                                                    if True
                                                        print('Condition met')
                                                        print('Hello, World!')
                                                        if True
                                                            print('Condition met')
                                                            if True
                                                                print('Condition met')
                                                                for i in range(5) print(i)
                                                                if True
                                                                    print('Condition met')
                                                                    class Bot
                                                                        def run(self)
                                                                                print('Running...')
                                                                                print('Hello, World!')
                                                                                def greet(name) return f'Hello {name}'
                                                                                print('Hello, World!')
                                                                                class Bot
                                                                                    def run(self)
                                                                                            print('Running...')
                                                                                            class Bot
                                                                                                def run(self)
                                                                                                        print('Running...')
                                                                                                        def greet(name) return f'Hello {name}'
                                                                                                        if True
                                                                                                            print('Condition met')
                                                                                                            def greet(name) return f'Hello {name}'
                                                                                                            for i in range(5) print(i)
                                                                                                            class Bot
                                                                                                                def run(self)
                                                                                                                        print('Running...')
                                                                                                                        print('Hello, World!')
                                                                                                                        print('Hello, World!')
                                                                                                                        for i in range(5) print(i)
                                                                                                                        class Bot
                                                                                                                            def run(self)
                                                                                                                                    print('Running...')
                                                                                                                                    class Bot
                                                                                                                                        def run(self)
                                                                                                                                                print('Running...')
                                                                                                                                                class Bot
                                                                                                                                                    def run(self)
                                                                                                                                                            print('Running...')
                                                                                                                                                            def greet(name) return f'Hello {name}'
                                                                                                                                                            class Bot
                                                                                                                                                                def run(self)
                                                                                                                                                                        print('Running...')
                                                                                                                                                                        for i in range(5) print(i)
                                                                                                                                                                        if True
                                                                                                                                                                            print('Condition met')
                                                                                                                                                                            if True
                                                                                                                                                                                print('Condition met')
                                                                                                                                                                                for i in range(5) print(i)
                                                                                                                                                                                def greet(name) return f'Hello {name}'
                                                                                                                                                                                print('Hello, World!')
                                                                                                                                                                                def greet(name) return f'Hello {name}'
                                                                                                                                                                                if True
                                                                                                                                                                                    print('Condition met')
                                                                                                                                                                                    def greet(name) return f'Hello {name}'
                                                                                                                                                                                    class Bot
                                                                                                                                                                                        def run(self)
                                                                                                                                                                                                print('Running...')
                                                                                                                                                                                                def greet(name) return f'Hello {name}'
                                                                                                                                                                                                class Bot
                                                                                                                                                                                                    def run(self)
                                                                                                                                                                                                            print('Running...')
                                                                                                                                                                                                            class Bot
                                                                                                                                                                                                                def run(self)
                                                                                                                                                                                                                        print('Running...')
                                                                                                                                                                                                                        def greet(name) return f'Hello {name}'
                                                                                                                                                                                                                        print('Hello, World!')
                                                                                                                                                                                                                        print('Hello, World!')
                                                                                                                                                                                                                        def greet(name) return f'Hello {name}'
                                                                                                                                                                                                                        class Bot
                                                                                                                                                                                                                            def run(self)
                                                                                                                                                                                                                                    print('Running...')
                                                                                                                                                                                                                                    class Bot
                                                                                                                                                                                                                                        def run(self)
                                                                                                                                                                                                                                                print('Running...')
                                                                                                                                                                                                                                                class Bot
                                                                                                                                                                                                                                                    def run(self)
                                                                                                                                                                                                                                                            print('Running...')
                                                                                                                                                                                                                                                            if True
                                                                                                                                                                                                                                                                print('Condition met')
                                                                                                                                                                                                                                                                class Bot
                                                                                                                                                                                                                                                                    def run(self)
                                                                                                                                                                                                                                                                            print('Running...')
                                                                                                                                                                                                                                                                            class Bot
                                                                                                                                                                                                                                                                                def run(self)
                                                                                                                                                                                                                                                                                        print('Running...')
                                                                                                                                                                                                                                                                                        for i in range(5) print(i)
                                                                                                                                                                                                                                                                                        class Bot
                                                                                                                                                                                                                                                                                            def run(self)
                                                                                                                                                                                                                                                                                                    print('Running...')
                                                                                                                                                                                                                                                                                                    print('Hello, World!')
                                                                                                                                                                                                                                                                                                    def greet(name) return f'Hello {name}'
                                                                                                                                                                                                                                                                                                    if True
                                                                                                                                                                                                                                                                                                        print('Condition met')
                                                                                                                                                                                                                                                                                                        if True
                                                                                                                                                                                                                                                                                                            print('Condition met')
                                                                                                                                                                                                                                                                                                            print('Hello, World!')
                                                                                                                                                                                                                                                                                                            class Bot
                                                                                                                                                                                                                                                                                                                def run(self)
                                                                                                                                                                                                                                                                                                                        print('Running...')
                                                                                                                                                                                                                                                                                                                        for i in range(5) print(i)
                                                                                                                                                                                                                                                                                                                        if True
                                                                                                                                                                                                                                                                                                                            print('Condition met')
                                                                                                                                                                                                                                                                                                                            if True
                                                                                                                                                                                                                                                                                                                                print('Condition met')
                                                                                                                                                                                                                                                                                                                                def greet(name) return f'Hello {name}'
                                                                                                                                                                                                                                                                                                                                for i in range(5) print(i)
                                                                                                                                                                                                                                                                                                                                for i in range(5) print(i)
                                                                                                                                                                                                                                                                                                                                print('Hello, World!')
                                                                                                                                                                                                                                                                                                                                def greet(name) return f'Hello {name}'
                                                                                                                                                                                                                                                                                                                                print('Hello, World!')
                                                                                                                                                                                                                                                                                                                                def greet(name) return f'Hello {name}'
                                                                                                                                                                                                                                                                                                                                class Bot
                                                                                                                                                                                                                                                                                                                                    def run(self)
                                                                                                                                                                                                                                                                                                                                            print('Running...')
                                                                                                                                                                                                                                                                                                                                            def greet(name) return f'Hello {name}'
                                                                                                                                                                                                                                                                                                                                            for i in range(5) print(i)
                                                                                                                                                                                                                                                                                                                                            print('Hello, World!')
                                                                                                                                                                                                                                                                                                                                            def greet(name) return f'Hello {name}'
                                                                                                                                                                                                                                                                                                                                            if True
                                                                                                                                                                                                                                                                                                                                                print('Condition met')
                                                                                                                                                                                                                                                                                                                                                def greet(name) return f'Hello {name}'
                                                                                                                                                                                                                                                                                                                                                for i in range(5) print(i)
                                                                                                                                                                                                                                                                                                                                                if True
                                                                                                                                                                                                                                                                                                                                                    print('Condition met')
                                                                                                                                                                                                                                                                                                                                                    print('Hello, World!')
                                                                                                                                                                                                                                                                                                                                                    def greet(name) return f'Hello {name}'
                                                                                                                                                                                                                                                                                                                                                    def greet(name) return f'Hello {name}'
                                                                                                                                                                                                                                                                                                                                                    if True
                                                                                                                                                                                                                                                                                                                                                        print('Condition met')
                                                                                                                                                                                                                                                                                                                                                        class Bot
                                                                                                                                                                                                                                                                                                                                                            def run(self)
                                                                                                                                                                                                                                                                                                                                                                    print('Running...')
                                                                                                                                                                                                                                                                                                                                                                    class Bot
                                                                                                                                                                                                                                                                                                                                                                        def run(self)
                                                                                                                                                                                                                                                                                                                                                                                print('Running...')
                                                                                                                                                                                                                                                                                                                                                                                if True
                                                                                                                                                                                                                                                                                                                                                                                    print('Condition met')
                                                                                                                                                                                                                                                                                                                                                                                    print('Hello, World!')
                                                                                                                                                                                                                                                                                                                                                                                    print('Hello, World!')
                                                                                                                                                                                                                                                                                                                                                                                    print('Hello, World!')
                                                                                                                                                                                                                                                                                                                                                                                    print('Hello, World!')
                                                                                                                                                                                                                                                                                                                                                                                    def greet(name) return f'Hello {name}'
                                                                                                                                                                                                                                                                                                                                                                                    def greet(name) return f'Hello {name}'
                                                                                                                                                                                                                                                                                                                                                                                    def greet(name) return f'Hello {name}'
                                                                                                                                                                                                                                                                                                                                                                                    print('Hello, World!')
                                                                                                                                                                                                                                                                                                                                                                                    def greet(name) return f'Hello {name}'
                                                                                                                                                                                                                                                                                                                                                                                    class Bot
                                                                                                                                                                                                                                                                                                                                                                                        def run(self)
                                                                                                                                                                                                                                                                                                                                                                                                print('Running...')
                                                                                                                                                                                                                                                                                                                                                                                                def greet(name) return f'Hello {name}'
                                                                                                                                                                                                                                                                                                                                                                                                if True
                                                                                                                                                                                                                                                                                                                                                                                                    print('Condition met')
                                                                                                                                                                                                                                                                                                                                                                                                    print('Hello, World!')
                                                                                                                                                                                                                                                                                                                                                                                                    for i in range(5) print(i)
                                                                                                                                                                                                                                                                                                                                                                                                    print('Hello, World!')
                                                                                                                                                                                                                                                                                                                                                                                                    print('Hello, World!')
                                                                                                                                                                                                                                                                                                                                                                                                    for i in range(5) print(i)
                                                                                                                                                                                                                                                                                                                                                                                                    class Bot
                                                                                                                                                                                                                                                                                                                                                                                                        def run(self)
                                                                                                                                                                                                                                                                                                                                                                                                                print('Running...')
                                                                                                                                                                                                                                                                                                                                                                                                                if True
                                                                                                                                                                                                                                                                                                                                                                                                                    print('Condition met')
                                                                                                                                                                                                                                                                                                                                                                                                                    for i in range(5) print(i)
                                                                                                                                                                                                                                                                                                                                                                                                                    print('Hello, World!')
                                                                                                                                                                                                                                                                                                                                                                                                                    for i in range(5) print(i)
                                                                                                                                                                                                                                                                                                                                                                                                                    if True
                                                                                                                                                                                                                                                                                                                                                                                                                        print('Condition met')
                                                                                                                                                                                                                                                                                                                                                                                                                        if True
                                                                                                                                                                                                                                                                                                                                                                                                                            print('Condition met')
                                                                                                                                                                                                                                                                                                                                                                                                                            class Bot
                                                                                                                                                                                                                                                                                                                                                                                                                                def run(self)
                                                                                                                                                                                                                                                                                                                                                                                                                                        print('Running...')
                                                                                                                                                                                                                                                                                                                                                                                                                                        class Bot
                                                                                                                                                                                                                                                                                                                                                                                                                                            def run(self)
                                                                                                                                                                                                                                                                                                                                                                                                                                                    print('Running...')
                                                                                                                                                                                                                                                                                                                                                                                                                                                    class Bot
                                                                                                                                                                                                                                                                                                                                                                                                                                                        def run(self)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                print('Running...')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                def greet(name) return f'Hello {name}'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                if True
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    print('Condition met')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    class Bot
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        def run(self)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                print('Running...')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                def greet(name) return f'Hello {name}'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                print('Hello, World!')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                class Bot
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    def run(self)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            print('Running...')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            print('Hello, World!')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            for i in range(5) print(i)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            def greet(name) return f'Hello {name}'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if True
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                print('Condition met')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                class Bot
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    def run(self)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            print('Running...')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if True
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                print('Condition met')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                for i in range(5) pri
'''