def fact(n):
    if n == 1:
        return 1
    else:
        return n * fact(n-1)

print(fact(5))
'''
class Bot
    def run(self)
            print('Running...')
            for i in range(5) print(i)
            if True
                print('Condition met')
                if True
                    print('Condition met')
                    for i in range(5) print(i)
                    if True
                        print('Condition met')
                        class Bot
                            def run(self)
                                    print('Running...')
                                    class Bot
                                        def run(self)
                                                print('Running...')
                                                for i in range(5) print(i)
                                                def greet(name) return f'Hello {name}'
                                                for i in range(5) print(i)
                                                class Bot
                                                    def run(self)
                                                            print('Running...')
                                                            class Bot
                                                                def run(self)
                                                                        print('Running...')
                                                                        print('Hello, World!')
                                                                        print('Hello, World!')
                                                                        for i in range(5) print(i)
                                                                        for i in range(5) print(i)
                                                                        if True
                                                                            print('Condition met')
                                                                            if True
                                                                                print('Condition met')
                                                                                print('Hello, World!')
                                                                                if True
                                                                                    print('Condition met')
                                                                                    class Bot
                                                                                        def run(self)
                                                                                                print('Running...')
                                                                                                for i in range(5) print(i)
                                                                                                if True
                                                                                                    print('Condition met')
                                                                                                    for i in range(5) print(i)
                                                                                                    for i in range(5) print(i)
                                                                                                    class Bot
                                                                                                        def run(self)
                                                                                                                print('Running...')
                                                                                                                def greet(name) return f'Hello {name}'
                                                                                                                for i in range(5) print(i)
                                                                                                                class Bot
                                                                                                                    def run(self)
                                                                                                                            print('Running...')
                                                                                                                            if True
                                                                                                                                print('Condition met')
                                                                                                                                for i in range(5) print(i)
                                                                                                                                class Bot
                                                                                                                                    def run(self)
                                                                                                                                            print('Running...')
                                                                                                                                            for i in range(5) print(i)
                                                                                                                                            for i in range(5) print(i)
                                                                                                                                            def greet(name) return f'Hello {name}'
                                                                                                                                            for i in range(5) print(i)
                                                                                                                                            def greet(name) return f'Hello {name}'
                                                                                                                                            if True
                                                                                                                                                print('Condition met')
                                                                                                                                                def greet(name) return f'Hello {name}'
                                                                                                                                                def greet(name) return f'Hello {name}'
                                                                                                                                                def greet(name) return f'Hello {name}'
                                                                                                                                                print('Hello, World!')
                                                                                                                                                def greet(name) return f'Hello {name}'
                                                                                                                                                def greet(name) return f'Hello {name}'
                                                                                                                                                print('Hello, World!')
                                                                                                                                                if True
                                                                                                                                                    print('Condition met')
                                                                                                                                                    print('Hello, World!')
                                                                                                                                                    for i in range(5) print(i)
                                                                                                                                                    class Bot
                                                                                                                                                        def run(self)
                                                                                                                                                                print('Running...')
                                                                                                                                                                class Bot
                                                                                                                                                                    def run(self)
                                                                                                                                                                            print('Running...')
                                                                                                                                                                            print('Hello, World!')
                                                                                                                                                                            print('Hello, World!')
                                                                                                                                                                            print('Hello, World!')
                                                                                                                                                                            print('Hello, World!')
                                                                                                                                                                            def greet(name) return f'Hello {name}'
                                                                                                                                                                            def greet(name) return f'Hello {name}'
                                                                                                                                                                            def greet(name) return f'Hello {name}'
                                                                                                                                                                            print('Hello, World!')
                                                                                                                                                                            for i in range(5) print(i)
                                                                                                                                                                            print('Hello, World!')
                                                                                                                                                                            class Bot
                                                                                                                                                                                def run(self)
                                                                                                                                                                                        print('Running...')
                                                                                                                                                                                        def greet(name) return f'Hello {name}'
                                                                                                                                                                                        for i in range(5) print(i)
                                                                                                                                                                                        def greet(name) return f'Hello {name}'
                                                                                                                                                                                        if True
                                                                                                                                                                                            print('Condition met')
                                                                                                                                                                                            print('Hello, World!')
                                                                                                                                                                                            if True
                                                                                                                                                                                                print('Condition met')
                                                                                                                                                                                                if True
                                                                                                                                                                                                    print('Condition met')
                                                                                                                                                                                                    def greet(name) return f'Hello {name}'
                                                                                                                                                                                                    print('Hello, World!')
                                                                                                                                                                                                    if True
                                                                                                                                                                                                        print('Condition met')
                                                                                                                                                                                                        class Bot
                                                                                                                                                                                                            def run(self)
                                                                                                                                                                                                                    print('Running...')
                                                                                                                                                                                                                    for i in range(5) print(i)
                                                                                                                                                                                                                    if True
                                                                                                                                                                                                                        print('Condition met')
                                                                                                                                                                                                                        print('Hello, World!')
                                                                                                                                                                                                                        if True
                                                                                                                                                                                                                            print('Condition met')
                                                                                                                                                                                                                            def greet(name) return f'Hello {name}'
                                                                                                                                                                                                                            def greet(name) return f'Hello {name}'
                                                                                                                                                                                                                            print('Hello, World!')
                                                                                                                                                                                                                            for i in range(5) print(i)
                                                                                                                                                                                                                            def greet(name) return f'Hello {name}'
                                                                                                                                                                                                                            print('Hello, World!')
                                                                                                                                                                                                                            for i in range(5) print(i)
                                                                                                                                                                                                                            class Bot
                                                                                                                                                                                                                                def run(self)
                                                                                                                                                                                                                                        print('Running...')
                                                                                                                                                                                                                                        def greet(name) return f'Hello {name}'
                                                                                                                                                                                                                                        print('Hello, World!')
                                                                                                                                                                                                                                        def greet(name) return f'Hello {name}'
                                                                                                                                                                                                                                        if True
                                                                                                                                                                                                                                            print('Condition met')
                                                                                                                                                                                                                                            def greet(name) return f'Hello {name}'
                                                                                                                                                                                                                                            for i in range(5) print(i)
                                                                                                                                                                                                                                            print('Hello, World!')
                                                                                                                                                                                                                                            print('Hello, World!')
                                                                                                                                                                                                                                            class Bot
                                                                                                                                                                                                                                                def run(self)
                                                                                                                                                                                                                                                        print('Running...')
                                                                                                                                                                                                                                                        print('Hello, World!')
                                                                                                                                                                                                                                                        print('Hello, World!')
                                                                                                                                                                                                                                                        class Bot
                                                                                                                                                                                                                                                            def run(self)
                                                                                                                                                                                                                                                                    print('Running...')
                                                                                                                                                                                                                                                                    class Bot
                                                                                                                                                                                                                                                                        def run(self)
                                                                                                                                                                                                                                                                                print('Running...')
                                                                                                                                                                                                                                                                                class Bot
                                                                                                                                                                                                                                                                                    def run(self)
                                                                                                                                                                                                                                                                                            print('Running...')
                                                                                                                                                                                                                                                                                            if True
                                                                                                                                                                                                                                                                                                print('Condition met')
                                                                                                                                                                                                                                                                                                class Bot
                                                                                                                                                                                                                                                                                                    def run(self)
                                                                                                                                                                                                                                                                                                            print('Running...')
                                                                                                                                                                                                                                                                                                            def greet(name) return f'Hello {name}'
                                                                                                                                                                                                                                                                                                            class Bot
                                                                                                                                                                                                                                                                                                                def run(self)
                                                                                                                                                                                                                                                                                                                        print('Running...')
                                                                                                                                                                                                                                                                                                                        print('Hello, World!')
                                                                                                                                                                                                                                                                                                                        def greet(name) return f'Hello {name}'
                                                                                                                                                                                                                                                                                                                        for i in range(5) print(i)
                                                                                                                                                                                                                                                                                                                        if True
                                                                                                                                                                                                                                                                                                                            print('Condition met')
                                                                                                                                                                                                                                                                                                                            def greet(name) return f'Hello {name}'
                                                                                                                                                                                                                                                                                                                            class Bot
                                                                                                                                                                                                                                                                                                                                def run(self)
                                                                                                                                                                                                                                                                                                                                        print('Running...')
                                                                                                                                                                                                                                                                                                                                        class Bot
                                                                                                                                                                                                                                                                                                                                            def run(self)
                                                                                                                                                                                                                                                                                                                                                    print('Running...')
                                                                                                                                                                                                                                                                                                                                                    if True
                                                                                                                                                                                                                                                                                                                                                        print('Condition met')
                                                                                                                                                                                                                                                                                                                                                        class Bot
                                                                                                                                                                                                                                                                                                                                                            def run(self)
                                                                                                                                                                                                                                                                                                                                                                    print('Running...')
                                                                                                                                                                                                                                                                                                                                                                    print('Hello, World!')
                                                                                                                                                                                                                                                                                                                                                                    print('Hello, World!')
                                                                                                                                                                                                                                                                                                                                                                    print('Hello, World!')
                                                                                                                                                                                                                                                                                                                                                                    print('Hello, World!')
                                                                                                                                                                                                                                                                                                                                                                    for i in range(5) print(i)
                                                                                                                                                                                                                                                                                                                                                                    print('Hello, World!')
                                                                                                                                                                                                                                                                                                                                                                    for i in range(5) print(i)
                                                                                                                                                                                                                                                                                                                                                                    def greet(name) return f'Hello {name}'
                                                                                                                                                                                                                                                                                                                                                                    if True
                                                                                                                                                                                                                                                                                                                                                                        print('Condition met')
                                                                                                                                                                                                                                                                                                                                                                        for i in range(5) print(i)
                                                                                                                                                                                                                                                                                                                                                                        print('Hello, World!')
                                                                                                                                                                                                                                                                                                                                                                        if True
                                                                                                                                                                                                                                                                                                                                                                            print('Condition met')
                                                                                                                                                                                                                                                                                                                                                                            if True
                                                                                                                                                                                                                                                                                                                                                                                print('Condition met')
                                                                                                                                                                                                                                                                                                                                                                                for i in range(5) print(i)
                                                                                                                                                                                                                                                                                                                                                                                print('Hello, World!')
                                                                                                                                                                                                                                                                                                                                                                                if True
                                                                                                                                                                                                                                                                                                                                                                                    print('Condition met')
                                                                                                                                                                                                                                                                                                                                                                                    for i in range(5) print(i)
                                                                                                                                                                                                                                                                                                                                                                                    def greet(name) return f'Hello {name}'
                                                                                                                                                                                                                                                                                                                                                                                    print('Hello, World!')
                                                                                                                                                                                                                                                                                                                                                                                    class Bot
                                                                                                                                                                                                                                                                                                                                                                                        def run(self)
                                                                                                                                                                                                                                                                                                                                                                                                print('Running...')
                                                                                                                                                                                                                                                                                                                                                                                                print('Hello, World!')
                                                                                                                                                                                                                                                                                                                                                                                                print('Hello, World!')
                                                                                                                                                                                                                                                                                                                                                                                                for i in range(5) print(i)
                                                                                                                                                                                                                                                                                                                                                                                                class Bot
                                                                                                                                                                                                                                                                                                                                                                                                    def run(self)
                                                                                                                                                                                                                                                                                                                                                                                                            print('Running...')
                                                                                                                                                                                                                                                                                                                                                                                                            def greet(name) return f'Hello {name}'
                                                                                                                                                                                                                                                                                                                                                                                                            for i in range(5) print(i)
                                                                                                                                                                                                                                                                                                                                                                                                            def greet(name) return f'Hello {name}'
                                                                                                                                                                                                                                                                                                                                                                                                            if True
                                                                                                                                                                                                                                                                                                                                                                                                                print('Condition met')
                                                                                                                                                                                                                                                                                                                                                                                                                class Bot
                                                                                                                                                                                                                                                                                                                                                                                                                    def run(self)
                                                                                                                                                                                                                                                                                                                                                                                                                            print('Running...')
                                                                                                                                                                                                                                                                                                                                                                                                                            for i in range(5) print(i)
                                                                                                                                                                                                                                                                                                                                                                                                                            if True
                                                                                                                                                                                                                                                                                                                                                                                                                                print('Condition met')
                                                                                                                                                                                                                                                                                                                                                                                                                                print('Hello, World!')
                                                                                                                                                                                                                                                                                                                                                                                                                                if True
                                                                                                                                                                                                                                                                                                                                                                                                                                    print('Condition met')
                                                                                                                                                                                                                                                                                                                                                                                                                                    for i in range(5) print(i)
                                                                                                                                                                                                                                                                                                                                                                                                                                    print('Hello, World!')
                                                                                                                                                                                                                                                                                                                                                                                                                                    if True
                                                                                                                                                                                                                                                                                                                                                                                                                                        print('Condition met')
                                                                                                                                                                                                                                                                                                                                                                                                                                        print('Hello, World!')
                                                                                                                                                                                                                                                                                                                                                                                                                                        def greet(name) return f'Hello {name}'
                                                                                                                                                                                                                                                                                                                                                                                                                                        class Bot
                                                                                                                                                                                                                                                                                                                                                                                                                                            def run(self)
                                                                                                                                                                                                                                                                                                                                                                                                                                                    print('Running...')
                                                                                                                                                                                                                                                                                                                                                                                                                                                    if True
                                                                                                                                                                                                                                                                                                                                                                                                                                                        print('Condition met')
                                                                                                                                                                                                                                                                                                                                                                                                                                                        def greet(name) return f'Hello {name}'
                                                                                                                                                                                                                                                                                                                                                                                                                                                        class Bot
                                                                                                                                                                                                                                                                                                                                                                                                                                                            def run(self)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    print('Running...')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    for i in range(5) print(i)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if True
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        print('Condition met')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        print('Hello, World!')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        print('Hello, World!')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        for i in range(5) print(i)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if True
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            print('Condition met')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            for i in range(5) print(i)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            for i in range(5) print(i)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            print('Hello, World!')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            class Bot
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                def run(self)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        print('Running...')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        print('Hello, World!')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        def greet(name) return f'Hello {name}'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        class Bot
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            def run(self)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    print('Running...')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    for i in range(5) print(i)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    print('Hello, World!')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    for i in range(5) print(i)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    print('Hello, World!')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    class Bot
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        def run(self)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                print('Running...')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                print('Hello, World!')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                def greet(name) return f'Hello {name}'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                print('Hello, World!')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                def greet(name) return f'Hello {name}'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                print('Hello, World!')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                def greet(name) return f'Hello {name}'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                print('Hello, World!')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                for i in range(5) print(i)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                class Bot
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    def run(self)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            print('Running...')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            def greet(name) return f'Hello {name}'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            class Bot
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                def run(self)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        print('Running...')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        print('Hello, World!')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        print('Hello, World!')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        for i in range(5) print(i)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if True
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            print('Condition met')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            def greet(name) return f'Hello {name}'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if True
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                print('Condition met')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                print('Hello, World!')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if True
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    print('Condition met')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    print('Hello, World!')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    print('Hello, World!')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    class Bot
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        def run(self)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                print('Running...)
'''