marks = []

f1 = int(input("Enter the first marks: "))
marks.append(f1)
f2 = int(input("Enter the second marks: "))
marks.append(f2)
f3 = int(input("Enter the third marks: "))
marks.append(f3)
f4 = int(input("Enter the fourth marks: "))
marks.append(f4)
f5 = int(input("Enter the fifth marks: "))
marks.append(f5)
f6 = int(input("Enter the sixth marks: "))
marks.append(f6)   
f7 = int(input("Enter the seventh marks: "))
marks.append(f7)
marks.sort()
print("The list of marks is:", marks)